config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    get 'ask', to: 'questions#ask'
    get 'answer', to:'questions#answer'

    # Generic syntax:
    # verb 'path', to: 'controller#action'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @ask = params[:ask]
    # raise
    if @ask == "I am going to work"
      @answer = "great"
    elsif @ask.include?("?")
      @answer = "Silly question, get dressed and go to work!."
    else
      @answer = " I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Stupid Coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="bloc">
<h2><%= @ask%></h2>
<h3>- You</h3>
</div>

<div class="yellowbloc">
<h2><%= @answer%></h2>
<h3>- Your coach</h3>
</div>



<%= link_to "ask a new question", ask_path %>

app/views/questions/ask.html.erb
<h2>Question</h2>
<form action="/answer" method="get">
  <input type="text" name="ask" value="<%= params[:ask] %>" placeholder="What's your question?">
  <input type="submit" value="Ask!">
</form>

<%= link_to "get the answer", answer_path %>